"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import TodoTracker

APP = ['TodoTracker.py']
DATA_FILES = []
OPTIONS = {}

setup(
    name='TodoTracker',
    version=TodoTracker.version,
    author='Ariana Giroux',
    author_email='ariana.giroux@gmail.com',
    url='https://github.com/EclectickMedia/TodoTracker',
    description='A simple todo tracking software.',
    long_description='A todo tracking software that searches regular text '
                     'files (like .py or .sh) files for the text `# TODO`, and '
                     'outputs the contents of any line found to a single file.',
    license='MIT',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.5'
    ],
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
