TODO MASTER (Fri Aug  5 02:38:00 2016)                  *Generated by github.com/eclectickmedia/todotracker*
--------


TodoTracker.py
--------
23:# TODO Include a Read me for the application.
26:This software is intended to be a low overhead, simple, and pythonic method of searching for `# TODO' tags out of a
31:presented by the search and finds `# TODO' tags in your software, then outputs them to the screen in a standardized,
34:This software rose due to a need for a simple software that can quickly, and cost effectively search for `# TODO' tags
69:parser.add_argument('-Q', '--quiet', help='Do not output \'# TODO\' items as they are found.', action='store_true')
130:                            if line.count('# TODO') > 0:
