TODOMASTER (Thu Aug  4 00:41:40 2016)                  *Generated by github.com/eclectickmedia/todotracker*
--------


TodoTracker.py
--------
22:# TODO Include a readme for the application.
30:presented by the search and finds `# TODO' tags in your software, then outputs them to the screen in a standardized,
33:This software rose due to a need for a simple software that can quickly, and cost effectively search for `# TODO' tags
68:parser.add_argument('-Q', '--quiet', help='Do not output \'# TODO\' items as they are found.', action='store_true')
129:                            if line.count('# TODO') > 0:
