TODOMASTER                  *Generated by github.com/eclectickmedia/todotracker*
--------


TodoTracker.py
--------
27:presented by the search and finds `# TODO' tags in your software, then outputs them to the screen in a standardized,
30:This software rose due to a need for a simple software that can quickly, and cost effectively search for `# TODO' tags
65:parser.add_argument('-Q', '--quiet', help='Do not output \'# TODO\' items as they are found.', action='store_true')
125:                            if line.count('# TODO') > 0:
